// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.1
// source: nice.proto

package nice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgId int32

const (
	MsgId_none          MsgId = 0 // proto3默认枚举从0开始 保留此项用于占位 它不会被自动注册
	MsgId_c2s_Heartbeat MsgId = 1 // 心跳 客户端 -> 服务器
	MsgId_s2c_Heartbeat MsgId = 2 // 心跳 服务器 -> 客户端
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0: "none",
		1: "c2s_Heartbeat",
		2: "s2c_Heartbeat",
	}
	MsgId_value = map[string]int32{
		"none":          0,
		"c2s_Heartbeat": 1,
		"s2c_Heartbeat": 2,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_nice_proto_enumTypes[0].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_nice_proto_enumTypes[0]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_nice_proto_rawDescGZIP(), []int{0}
}

type C2S_Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_Heartbeat) Reset() {
	*x = C2S_Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Heartbeat) ProtoMessage() {}

func (x *C2S_Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_nice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Heartbeat.ProtoReflect.Descriptor instead.
func (*C2S_Heartbeat) Descriptor() ([]byte, []int) {
	return file_nice_proto_rawDescGZIP(), []int{0}
}

type S2C_Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 当前服务器时间戳
}

func (x *S2C_Heartbeat) Reset() {
	*x = S2C_Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Heartbeat) ProtoMessage() {}

func (x *S2C_Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_nice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Heartbeat.ProtoReflect.Descriptor instead.
func (*S2C_Heartbeat) Descriptor() ([]byte, []int) {
	return file_nice_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_nice_proto protoreflect.FileDescriptor

var file_nice_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x69,
	0x63, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x22, 0x2d, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2a, 0x37, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x6e,
	0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x63, 0x32, 0x73, 0x5f, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x73, 0x32, 0x63, 0x5f,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x10, 0x02, 0x42, 0x07, 0x5a, 0x05, 0x2f,
	0x6e, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nice_proto_rawDescOnce sync.Once
	file_nice_proto_rawDescData = file_nice_proto_rawDesc
)

func file_nice_proto_rawDescGZIP() []byte {
	file_nice_proto_rawDescOnce.Do(func() {
		file_nice_proto_rawDescData = protoimpl.X.CompressGZIP(file_nice_proto_rawDescData)
	})
	return file_nice_proto_rawDescData
}

var file_nice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nice_proto_goTypes = []interface{}{
	(MsgId)(0),            // 0: nice.MsgId
	(*C2S_Heartbeat)(nil), // 1: nice.C2S_Heartbeat
	(*S2C_Heartbeat)(nil), // 2: nice.S2C_Heartbeat
}
var file_nice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nice_proto_init() }
func file_nice_proto_init() {
	if File_nice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nice_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nice_proto_goTypes,
		DependencyIndexes: file_nice_proto_depIdxs,
		EnumInfos:         file_nice_proto_enumTypes,
		MessageInfos:      file_nice_proto_msgTypes,
	}.Build()
	File_nice_proto = out.File
	file_nice_proto_rawDesc = nil
	file_nice_proto_goTypes = nil
	file_nice_proto_depIdxs = nil
}
