// Code generated by protoc-gen-autoregister. DO NOT EDIT.
package nice

import (
	"github.com/murang/potato/pb"
	"reflect"
)

func init() {
	pb.RegisterMsg(uint32(MsgId_c2s_Heartbeat), reflect.TypeOf(C2S_Heartbeat{}))
	pb.RegisterMsg(uint32(MsgId_s2c_Heartbeat), reflect.TypeOf(S2C_Heartbeat{}))
}
